### ISSUE TITLE
KeyError 

### ISSUE THREAD

**Issue by DaWe35** [oliver-zehentleitner/unicorn-binance-websocket-api#82]
Reproduce: `python example_stream_everything.py` and wait for 3-6 seconds

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\unicorn_binance_websocket_api\unicorn_binance_websocket_api_manager.py", line 489, in _test_if_alive
    self.keepalive_streams_list[testalive_streams_id]['last_heartbeat'] = time.time()
KeyError: 1591447126.1199386
```

**Comment by miraclix** [comment]
I know, I pushed it to github yesterday evening but it's not ready

Am 6. Juni 2020 14:42:27 MESZ schrieb DaWe <notifications@github.com>:
>Reproduce: `python example_stream_everything.py` and wait for 3-6
>seconds
>
>```
>Exception in thread Thread-4:
>Traceback (most recent call last):
>File
>"C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\threading.py",
>line 917, in _bootstrap_inner
>    self.run()
>File
>"C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\threading.py",
>line 865, in run
>    self._target(*self._args, **self._kwargs)
>File
>"C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\site-packages\unicorn_binance_websocket_api\unicorn_binance_websocket_api_manager.py",
>line 489, in _test_if_alive
>self.keepalive_streams_list[testalive_streams_id]['last_heartbeat'] =
>time.time()
>KeyError: 1591447126.1199386
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/82

Oliver Zehentleitner

**Comment by oliver-zehentleitner** [comment]
I know, I pushed it to github yesterday evening but it's not ready

**Comment by DaWe35** [comment]
Then sorry, maybe not a breaking thing. Would be nice to push a release if it's stable, the Installion->From source of the latest release with PIP from Github->Windows method des not works.
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/archive/1.11.0.tar.gz `404`

**Comment by oliver-zehentleitner** [comment]
hi dawe! 

in general just go to releases and look what the last version number is:
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/tags

but this release is still having this bug:
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/45

i wrote update that i test here since 4 days and its pretty stable, i hope i solved the issue 45 with this. till now its looking good!

So I recommend installing this commit https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/commit/bbdef1f73b9f9d92ef04946e97325d926b0a39de 

I need to make more tests then i will release a final stable version. i guess it will take one week if i dont find more bugs.
